sftp:
  hostname: "10.1.1.10"
  sshPort: 22
  username: "root"
  password: "root"

sync:
  - name: "sync 1"
    sourcePath: "/tmp/test1"
    targetPath: "/tmp/test1"
  - name: "sync 2"
    sourcePath: "/tmp/test2"
    targetPath: "/tmp/test2"

ignoreFiles:
  - ".svn"
  - ".git"
  - ".idea"
  - ".swp"
  - ".swx"

log:
  appName: app
  development: true
  # Either "error", "warn", "info", "debug", default is "info"
  level: debug
  logFileDir: ./logs
  infoFileName: info.log
  warnFileName: warn.log
  errorFileName: error.log
  debugFileName: debug.log
  maxAge: 100
  maxBackups: 60
  maxSize: 30

notify:
  isEnable: true
  notifyType: email
  email:
    emailSubject: "文件发生变更"
    emailHost: "smtp.163.com"
    emailPort: 25
    emailUser: "xxx@163.com"
    emailPwd: "xxxxxx"
    toEmail: "xxx@qq.com"
