sftp:
  hostname: "10.1.1.10"
  sshPort: 22
  username: "root"
  password: "root"

sync:
  - name: "sync 1"
    sourcePath: "/tmp/test"
    targetPath: "/tmp/test"

ignoreFiles:
  - ".svn"
  - ".git"
  - ".idea"
  - ".swp"
  - ".swx"

log:
  appName: app
  development: true
  # Either "error", "warn", "info", "debug", default is "info"
  level: debug
  logFileDir: ./logs
  infoFileName: info.log
  warnFileName: warn.log
  errorFileName: error.log
  debugFileName: debug.log
  maxAge: 100
  maxBackups: 60
  maxSize: 30

# 消息推送
notify:
  # 是否开启推送服务
  isEnable: true
  # 目前支持 smtp 邮箱, wechat, wechatbot, dingtalkbot, feishubot
  notifyType: email
  # smtp 邮箱配置
  email:
    # 邮件主题
    subject: "文件发生变更"
    # 邮箱域名 smtp.xxx.com
    host: "smtp.163.com"
    # 通信端口
    port: 25
    # 邮箱地址 xxx@xxx.com
    from: "xxx@163.com"
    # 邮箱授权码（并不一定是邮箱密码） xxxxxx
    password: "xxxxxx"
    # 邮箱推送消息接收人, 可填写多个接收人
    to:
      - "xxx@qq.com"
  # wechat 配置
  wechat:
    accessTokenUrl: "https://qyapi.weixin.qq.com/cgi-bin/gettoken"
    sendUrl: "https://qyapi.weixin.qq.com/cgi-bin/message/send"
    # 企业ID，获取方式参考：术语说明-corpid(https://work.weixin.qq.com/api/doc/90000/90135/91039#14953/corpid)
    corpId: "xxxxxx"
    # 应用的凭证密钥，获取方式参考：术语说明-secret(https://work.weixin.qq.com/api/doc/90000/90135/91039#14953/secret)
    corpSecret: "xxxxxx"
    # 指定接收消息的成员，成员ID列表（多个接收者用'|'分隔，最多支持1000个）。特殊情况：指定为"@all"，则向该企业应用的全部成员发送
    toUser: "xxx"
    # 企业应用的id，整型。企业内部开发，可在应用的设置页面查看
    agentId: 1000000
  # wechat 机器人配置
  wechatbot:
    webHookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send"
    # 在终端某个群组添加机器人之后，创建者可以在机器人详情页看的该机器人特有的webhookurl
    key: "xxxxxx"
    # userid的列表，提醒群中的指定成员(@某个成员)，@all表示提醒所有人，如果开发者获取不到userid，可以使用mentioned_mobile_list
    mentionedList:
      - "xxx"
    # 手机号列表，提醒手机号对应的群成员(@某个成员)，@all表示提醒所有人
    mentionedMobileList:
      - ""
  # dingtalk 机器人配置
  dingtalkbot:
    webHookUrl: "https://oapi.dingtalk.com/robot/send"
    accessToken: "bf29f17ef2972180bacad9adf19412f7728e5b336fcb4c152af5be8a88888888"
    signToken: "SEC3383b31ef94081d10e5ae8c009923d738c4b92539746b40c3aec2c8e88888888"
    atUserIds:
      - "xxx"
    atMobiles:
      - ""
    isAtAll: false