sftp:
  hostname: "10.1.1.10"
  sshPort: 22
  username: "root"
  password: "root"

sync:
  - name: "sync 1"
    sourcePath: "/tmp/test1"
    targetPath: "/tmp/test1"
  - name: "sync 2"
    sourcePath: "/tmp/test2"
    targetPath: "/tmp/test2"

ignoreFiles:
  - ".svn"
  - ".git"
  - ".idea"
  - ".swp"
  - ".swx"

log:
  appName: app
  development: true
  # Either "error", "warn", "info", "debug", default is "info"
  level: debug
  logFileDir: ./logs
  infoFileName: info.log
  warnFileName: warn.log
  errorFileName: error.log
  debugFileName: debug.log
  maxAge: 100
  maxBackups: 60
  maxSize: 30

# 消息推送
notify:
  # 是否开启推送服务
  isEnable: true
  # 目前支持 smtp 邮箱,dingtalk
  notifyType: email
  # smtp 邮箱配置
  email:
    # 邮件主题
    emailSubject: "文件发生变更"
    # 邮箱域名 smtp.xx.com
    emailHost: "smtp.163.com"
    # 通信端口
    emailPort: 25
    # 邮箱地址 xxx@xx.com
    emailUser: "xxx@163.com"
    # 邮箱授权码（并不一定是邮箱密码） xxxxxx
    emailPwd: "xxxxxx"
    # 邮箱推送消息接收人
    toEmail: "xxx@qq.com"
  # wechat 配置
  wechat:
    accessTokenUrl: "https://qyapi.weixin.qq.com/cgi-bin/gettoken"
    sendUrl: "https://qyapi.weixin.qq.com/cgi-bin/message/send"
    # 企业ID，获取方式参考：术语说明-corpid(https://work.weixin.qq.com/api/doc/90000/90135/91039#14953/corpid)
    corpId: "xxxxxx"
    # 应用的凭证密钥，获取方式参考：术语说明-secret(https://work.weixin.qq.com/api/doc/90000/90135/91039#14953/secret)
    corpSecret: "xxxxxx"
    # 指定接收消息的成员，成员ID列表（多个接收者用'|'分隔，最多支持1000个）。特殊情况：指定为"@all"，则向该企业应用的全部成员发送
    toUser: "xxx"
    # 企业应用的id，整型。企业内部开发，可在应用的设置页面查看
    agentId: 1000000
